districts:
   # World Name where Districts will operate
   worldName: world
   # Starting blocks - the number of blocks a player will get at the start
   beginningblocks: 25


   # Visulizations - on or off
   showvisualization: true
   # Visualization material
   # Can be anything, but must be solid.
   # Good ones - GLOWSTONE, DIAMOND_BLOCK, GOLD_BLOCK, etc.
   # Default is REDSTONE_BLOCK
   visualblock: DIAMOND_BLOCK


   # Who gets blocks and how often
   # permission: <number of blocks>:<max>
   # List permission and how many blocks they get every tick and the maximum #
   # The permission can be anything you like, but you have to add it to the
   # players using a permissions plugin or other plugin.
   blockgroups:
     districts.player: 1:100
     districts.advancedplayer: 2:200
     districts.vip: 3:300
     districts.donor: 20:500
     districts.superdonor: 100:1000
   # How often to give out the blocks in minutes, if zero, blocks will never be given
   blocktick: 1

   # How often to check leases in hours. If this is 0, then leases will be checked
   # once when the plugin is loaded. If your server is automatically reset every day
   # this may be sufficient. The smaller this number, the quicker a lease will expire
   # after the deadline. 12 hours should be sufficient.
   checkleases: 12

   ### Default settings for districts. Owners will be able to customize the settings
   ### using the control panel
   #[true/false] PVP is allowed or denied.
   allowPvP: false
   # Other players can break blocks or not or generally damage things
   allowbreakblocks: false
   # Other players can place blocks
   allowplaceblocks: false
   # Allow players to be able to sleep in beds not on their island
   allowbeduse: false
   # Allow players to use buckets, either fill or dump them
   allowbucketuse: false
   # Allow players to shear sheep
   allowshearing: false
   # Allow players to throw enderpearls and teleport
   allowenderpearls: false
   # Allow players to use doors or trapdoors. If a door is operated by a button or redstone, this does not count
   allowdooruse: false
   # Allow players to use levers or buttons
   allowleverbuttonuse: false
   # Allow players to trample crops
   allowcroptrample: false
   # Allow players to access chests of any kind, droppers, dispensers and hoppers
   allowchestaccess: false
   # Allow players to access furnaces
   allowfurnaceuse: false
   # Allow players to adjust diodes or comparators
   allowredstone: false
   # Allow players to use jukeboxes, eject discs and hit note blocks
   allowmusic: false
   # Allow players to use crafting benches
   allowcrafting: true
   # Allow players to use cauldrons and brewing stands
   allowbrewing: false
   # Allow gates to be used
   allowgateuse: false
   # Allow non-monster mobs to be hurt
   allowhurtmobs: false
   