name: Districts
main: com.wasteofplastic.districts.Districts
version: 0.8
description: Districts
author: Tastybento
depend: [Vault]
softdepend: [WorldGuard]
commands:
    district:
        description: Main player command
        aliases: [dist, d]
        usage:  |
             /district help
    dadmin:
        description: Admin commands
        usage:  |
            /dadmin
permissions:    
  districts.player:
     description: Gives access to basic player commands
     default: true
  districts.advancedplayer:
     description: Gives access to advanced player commands (buy, sell, rent)
     default: false  
  districts.buyblocks:
     description: Enable block purchasing
     default: false   
  districts.admin:
     description: Gives access to admin commands
     default: op


